const DEFAULT_PRODUCTS=[
 {id:'p1',name:'Oxford Executive',category:'Formales',price:239,oldPrice:279,emoji:'👞',sizes:[39,40,41,42,43],stock:12,badge:'MÁS VENDIDO',sku:'PG-FOR-001'},
 {id:'p2',name:'Urban White',category:'Zapatillas',price:179,emoji:'👟',sizes:[36,37,38,39,40,41],stock:18,badge:'NUEVO',sku:'PG-ZAP-002'},
 {id:'p3',name:'Chelsea Noir',category:'Botines',price:269,emoji:'🥾',sizes:[38,39,40,41,42],stock:7,badge:'PREMIUM',sku:'PG-BOT-003'},
 {id:'p4',name:'Loafer Cacao',category:'Casuales',price:199,emoji:'👞',sizes:[38,39,40,41,42,43],stock:15,sku:'PG-CAS-004'},
 {id:'p5',name:'Runner Graphite',category:'Zapatillas',price:189,oldPrice:219,emoji:'👟',sizes:[37,38,39,40,41,42],stock:9,badge:'OFERTA',sku:'PG-ZAP-005'},
 {id:'p6',name:'Bota Terracota',category:'Botines',price:289,emoji:'🥾',sizes:[36,37,38,39,40],stock:5,sku:'PG-BOT-006'}
];
const money=n=>`S/ ${Number(n).toFixed(2)}`; const getProducts=()=>JSON.parse(localStorage.getItem('pg_products')||'null')||DEFAULT_PRODUCTS;let cart=JSON.parse(localStorage.getItem('pg_cart')||'[]');let selected={};
const $=s=>document.querySelector(s);if($('#filters')){const categories=['Todos',...new Set(getProducts().map(p=>p.category))];
const menuButton=$('#menuButton'),mainNav=$('#mainNav');menuButton.onclick=()=>{const open=mainNav.classList.toggle('open');menuButton.setAttribute('aria-expanded',String(open));menuButton.textContent=open?'×':'☰'};mainNav.onclick=()=>{mainNav.classList.remove('open');menuButton.setAttribute('aria-expanded','false');menuButton.textContent='☰'};
$('#filters').innerHTML=categories.map((c,i)=>`<button class="${i?'':'active'}" data-cat="${c}">${c}</button>`).join('');
$('#size').innerHTML+=[...new Set(getProducts().flatMap(p=>p.sizes))].sort().map(s=>`<option>${s}</option>`).join('');let activeCat='Todos';
function render(){let list=getProducts().filter(p=>(activeCat==='Todos'||p.category===activeCat)&&p.price<=+$('#price').value&&(!$('#size').value||p.sizes.includes(+$('#size').value))&&(p.name+' '+p.category+' '+p.sku).toLowerCase().includes($('#search').value.toLowerCase()));const sort=$('#sort').value;list.sort((a,b)=>sort==='low'?a.price-b.price:sort==='high'?b.price-a.price:sort==='name'?a.name.localeCompare(b.name):0);$('#resultCount').textContent=`${list.length} modelos disponibles`;$('#products').innerHTML=list.map(p=>`<article class="product">${p.badge?`<span class="badge">${p.badge}</span>`:''}<div class="product-visual">${p.emoji||'👞'}</div><div class="product-info"><small>${p.category} · ${p.sku}</small><h3>${p.name}</h3><span class="price">${money(p.price)}</span>${p.oldPrice?`<span class="old">${money(p.oldPrice)}</span>`:''}<div class="sizes" aria-label="Elegir talla">${p.sizes.map(s=>`<button data-size="${s}" data-id="${p.id}" class="${selected[p.id]===s?'selected':''}">${s}</button>`).join('')}</div><button class="add" data-add="${p.id}" ${p.stock<1?'disabled':''}>${p.stock<1?'Agotado':'Agregar al carrito'}</button></div></article>`).join('')||'<div class="empty">No encontramos productos con esos filtros.</div>'}
function save(){localStorage.setItem('pg_cart',JSON.stringify(cart));renderCart()}function renderCart(){const products=getProducts();$('#cartCount').textContent=cart.reduce((a,x)=>a+x.qty,0);$('#cartItems').innerHTML=cart.length?cart.map(x=>{const p=products.find(p=>p.id===x.id)||x;return `<div class="cart-row"><div class="thumb">${p.emoji||'👞'}</div><div><b>${p.name}</b><small>Talla ${x.size} · ${money(p.price)}</small><div class="qty"><button data-minus="${x.id}|${x.size}">−</button> ${x.qty} <button data-plus="${x.id}|${x.size}">+</button></div></div><button data-remove="${x.id}|${x.size}">×</button></div>`}).join(''):'<div class="empty">Tu carrito está vacío.<br><small>Elige un modelo para comenzar.</small></div>';$('#subtotal').textContent=money(cart.reduce((a,x)=>{const p=products.find(p=>p.id===x.id)||x;return a+p.price*x.qty},0))}
function openCart(show=true){$('#cart').classList.toggle('open',show);$('#overlay').classList.toggle('show',show)}function toast(msg){let t=document.createElement('div');t.className='toast';t.textContent=msg;document.body.append(t);requestAnimationFrame(()=>t.classList.add('show'));setTimeout(()=>{t.classList.remove('show');setTimeout(()=>t.remove(),300)},1800)}
$('#products').onclick=e=>{const size=e.target.dataset.size;if(size){selected[e.target.dataset.id]=+size;render()}const id=e.target.dataset.add;if(id){const p=getProducts().find(x=>x.id===id);if(!selected[id])return toast('Selecciona una talla');const existing=cart.find(x=>x.id===id&&x.size===selected[id]);existing?existing.qty++:cart.push({id,size:selected[id],qty:1,name:p.name,price:p.price,emoji:p.emoji});save();toast('Producto agregado')}};
$('#filters').onclick=e=>{if(!e.target.dataset.cat)return;activeCat=e.target.dataset.cat;[...$('#filters').children].forEach(b=>b.classList.toggle('active',b===e.target));render()};['search','price','size','sort'].forEach(id=>$('#'+id).addEventListener(id==='search'?'input':'change',()=>{if(id==='price')$('#priceOut').textContent=`S/ ${$('#price').value}`;render()}));
$('#openCart').onclick=()=>openCart();$('#closeCart').onclick=$('#overlay').onclick=()=>openCart(false);$('#clearCart').onclick=()=>{cart=[];save()};$('#cartItems').onclick=e=>{const key=e.target.dataset.remove||e.target.dataset.minus||e.target.dataset.plus;if(!key)return;const [id,size]=key.split('|');const i=cart.findIndex(x=>x.id===id&&x.size==size);if(e.target.dataset.plus)cart[i].qty++;else if(e.target.dataset.minus&&cart[i].qty>1)cart[i].qty--;else cart.splice(i,1);save()};
const phone=localStorage.getItem('pg_whatsapp')||'51999999999';$('#whatsapp').href=`https://wa.me/${phone}?text=${encodeURIComponent('Hola, deseo información sobre sus calzados.')}`;$('#checkout').onclick=()=>{if(!cart.length)return toast('Tu carrito está vacío');const ps=getProducts();const lines=cart.map(x=>{const p=ps.find(p=>p.id===x.id)||x;return `• ${p.name} | Talla ${x.size} | ${x.qty} x ${money(p.price)}`});const total=cart.reduce((a,x)=>a+(ps.find(p=>p.id===x.id)||x).price*x.qty,0);window.open(`https://wa.me/${phone}?text=${encodeURIComponent(`Hola, deseo realizar este pedido:\n\n${lines.join('\n')}\n\nSubtotal: ${money(total)}\n\n¿Podrían confirmarme disponibilidad y costo de envío?`)}`,'_blank')};render();renderCart();}
